Basic UI
tonnymuchui/OOP-school-library pull request #4
Opened 2023-03-23 22:02 UTC by tonnymuchui

- Create an app.rb :heavy_check_mark: 
- Define the entry point, `main.rb` :heavy_check_mark:

2023-03-23 22:23 UTC, mikethreels requested changes
Hi Tonny, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 22:23 UTC, mikethreels commented on app.rb
> +    teacher = Teacher.new(age, name, specialization)
- [ ] when creating a new teacher you are sending the age, name and specialization as arguments in that order, however, if you go to the teacher class you can see that it takes the argument in a different order therefor the application, at the moment, is saving the specialization as the name of the teacher. to solve this you can just switch the arguments you sent like this:
```
teacher = Teacher.new(age, specialization, name)
```

2023-03-23 22:23 UTC, mikethreels commented on app.rb
> +      return
- [ ] please do not exclude the users who have the can_use_services? set to no. as you can see in [the UI example ](https://www.youtube.com/watch?v=vkkgrhD6aXQ&ab_channel=EmiliaAndrzejewska)provided by Microverse these users should be included in the listing when creating a rental as well.

2023-03-25 04:29 UTC, uwadonat approved these changes
## Hi @tonnymuchui, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Correct workflow was used ✔️
- Good commit history ✔️

![approval](https://user-images.githubusercontent.com/65860678/227696039-455022c5-fd85-4779-8561-f3bee235c31f.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-25 05:02 UTC, merged